drop dependency on efitools

diff --git a/arch-secure-boot b/arch-secure-boot
--- a/arch-secure-boot
+++ b/arch-secure-boot
@@ -4,7 +4,8 @@ set -e
 
 DIR="/etc/arch-secure-boot"
 KEYSDIR="$DIR/keys"
-mkdir -p "$DIR" "$KEYSDIR"
+SBKEYSDIR="/etc/secureboot/keys"
+mkdir -p "$DIR" "$KEYSDIR" "$SBKEYSDIR"
 
 [ -f "$DIR/config" ] && source "$DIR/config"
 
@@ -114,12 +115,9 @@ case "$1" in
     enroll-keys)
         echo "Enrolling Secure Boot keys..."
 
-        find "$KEYSDIR" -mindepth 1 | read || error "Error: keys are not generated yet."
+        find "$SBKEYSDIR" -mindepth 2 | read || error "Error: keys are not generated yet."
 
-        cd "$KEYSDIR"
-        efi-updatevar -e -f KEK.esl KEK
-        efi-updatevar -e -f db.esl db
-        efi-updatevar -f PK.auth PK
+        sbkeysync --verbose --pk
         ;;
 
     generate-keys)
@@ -127,16 +125,24 @@ case "$1" in
 
         cd "$KEYSDIR"
 
-        uuid="$(uuidgen --random)"
-        echo "$uuid" > uuid
+        uuidgen > uuid
+        read uuid < uuid
 
-        for key in PK KEK db; do
+        for pair in PK=PK KEK=PK db=KEK; do
+            key="${pair%=*}"
+            from="${pair#*=}"
+
             openssl req -new -x509 -newkey rsa:4096 -subj "/CN=SecureBoot $key/" -keyout "$key.key" -out "$key.crt" -days 3650 -nodes -sha256
-            cert-to-efi-sig-list -g "$uuid" "$key.crt" "$key.esl"
-            sign-efi-sig-list -k "$key.key" -c "$key.crt" "$key" "$key.esl" "$key.auth"
-        done
+            openssl x509 -in "$key.crt" -inform PEM -out "$key.der" -outform DER
 
-        chmod 0400 *.{key,auth}
+            sbsiglist --owner "$uuid" --type x509 --output "$key.esl" "$key.der"
+            sbvarsign --key "$from.key" --cert "$from.crt" --output "$key.auth" "$key" "$key.esl"
+
+            chmod 0400 "$key".{key,auth}
+
+            mkdir -p "$SBKEYSDIR/$key/"
+            cp "$key.auth" "$SBKEYSDIR/$key/"
+        done
         ;;
 
     *)
